import certrender from '../assets/images/certrender.png';
import certrob from '../assets/images/certrobotica.png';
import certsql from  '../assets/images/certsql.png';


export const educationList =[
    {
        id:1,
        academic_school: 'Universidad Autónoma de Nuevo León',
        title:"Bachelor's degree / Computer Sciences",
        location:'San Nicolas de los Garza, N.L, México',
        certificate_number:'incomplete',
        path:'',
        date:'2019-2019',
    },
    {
        id:2,
        academic_school: 'Instituto de Especialización para Ejecutivos',
        title:'Máster degree / Tax laws',
        location:'Monterrey N.L, México',
        certificate_number:'incomplete',
        path:'',
        date:'2015-2016',
    },
    {
        id:3,
        academic_school: 'Universidad Metropolitana de Monterrey',
        title:"Bachelor's degree / Accountant",
        location:'Monterrey N.L, México',
        certificate_number:'complete',
        path:'',
        date:'Jan-07-Dec-09',
    },
    {
        id:4,
        academic_school: 'WYWM',
        title:'Linux Fundamentals',
        location:'Online',
        certificate_number:'f934a1520c8e',
        path:'',
        date:'Oct-23',
    },
    
    {
        id: 5,
        academic_school: 'WYWM',
        title:'Networking Fundamentals',
        location:'Online',
        certificate_number:'5eacec713c89',
        path:'',
        date:'Oct-23',
    },
    
    {
        id:6,
        academic_school: 'Codecademy',
        title:'Deploying with Render Course',
        location:'Online',
        certificate_number:'path',
        path:certrender,
        date:'Oct-23',
    },
    
    {
        id:7,
        academic_school: 'WYWM',
        title:'Reporting with Power BI',
        location:'Online',
        certificate_number:'7cc220f5c8cd',
        path:'',
        date:'Sep-23',
    },
    {
        id:8,
        academic_school: 'WYWM',
        title:'Introduction to Data Engineering',
        location:'Online',
        certificate_number:'566864db6387',
        path:'',
        date:'Sep-23',
    },
    
    {
        id:9,
        academic_school: 'WYWM',
        title:'SQL for Data Analysis and Development',
        location:'Online',
        certificate_number:'9525fc90390b',
        path:'',
        date:'Sep-23',
    },
    
    {
        id:10,
        academic_school: 'WYWM',
        title:'Data Visualization with Tableau',
        location:'Online',
        certificate_number:'5ffb8eacc095',
        path:'',
        date:'Aug-23',
    },
    
    {
        id:11,
        academic_school: 'WYWM',
        title:'Data Visualization with Power BI',
        location:'Online',
        certificate_number:'f7ecb28fa8d3',
        path:'',
        date:'Jul-23',
    },
    
    {
        id:12,
        academic_school: 'WYWM',
        title:'Data Analysis with Excel',
        location:'Online',
        certificate_number:'6dee5f23108b',
        path:'',
        date:'Jul-23',
    },
    {
        id:13,
        academic_school: 'WYWM',
        title:'Data Foundations',
        location:'Online',
        certificate_number:'57f19baf3af5',
        path:'',
        date:'Jun-23',
    },
    {
        id:14,
        academic_school: 'Udacity/Bertelsmann',
        title:'Next Generation Tech Booster Scholarship SQL Challenge',
        location:'Online',
        certificate_number:'path',
        path:'',
        date:'Jan-23',
    },
    {
        id:15,
        academic_school: 'Codecademy',
        title:'SQL',
        location:'Online',
        certificate_number:'path',
        path:certsql,
        date:'Oct-22',
    },
    {
        id:16,
        academic_school: 'Programming Hub',
        title:'Data Structure and Algorithms',
        location:'Online',
        certificate_number:'1652124072667',
        path:'',
        date:'Sep-22',
        
    },
    {
        id:17,
        academic_school: 'Universal Class',
        title:'Accounting & Bookkeeping 101',
        location:'Online',
        certificate_number:'D1ATPPJ6A394458',
        path:'',
        date:'Jun-22',
    },
    {
        id:18,
        academic_school: 'Programming Hub',
        title:'Data Science',
        location:'Online',
        certificate_number:'1649013602482',
        path:'',
        date:'Mar-22',
    },
    {
        id:19,
        academic_school: 'Programming Hub',
        title:'GIT',
        location:'Online',
        certificate_number:'1646726764226',
        path:'',
        date:'Mar-22',
    },
    {
        id:20,
        academic_school: 'Instituto de Especialización para Ejecutivos',
        title:'Seminario en Impuestos',
        location:'Online',
        certificate_number:'Constancia 5398',
        path:'',
        date:'Mar-22',
    },
    {
        id:21,
        academic_school: 'MIMO',
        title:'SQL',
        location:'Online',
        certificate_number:'path',
        path:'',
        date:'Dec-21',
    },
    {
        id:22,
        academic_school: 'MIMO',
        title:'Web Development',
        location:'Online',
        certificate_number:'path',
        path:'',
        date:'Dec-21',
    },
    {
        id:23,
        academic_school: 'MIMO',
        title:'Python',
        location:'Online',
        certificate_number:'path',
        path:'',
        date:'Dec-21',
    },
    {
        id:24,
        academic_school: 'ARACT',
        title:'Robotica Aplicada basico',
        location:'Online',
        certificate_number:'path',
        path:certrob,
        date:'Jan-21',
    },
    {
        id:25,
        academic_school: 'ACAMICA',
        title:'Full Stack Web Developer',
        location:'Online',
        certificate_number:'certificate pending',
        path:'',
        date:'Nov-20',
    },
    {
        id:26,
        academic_school: 'ICET',
        title:'Formacion de Instructores',
        location:'Online',
        certificate_number:'Diploma 33238-D-18',
        path:'',
        date:'Aug-18',
    },
]